#!/bin/bash

# Variables
PATH_CONFIGURE_DIR='/etc/smilart';
CLUSTER_INSTALLED="$PATH_CONFIGURE_DIR/cluster_installed";
SKYDNS_CONFIGURED="$PATH_CONFIGURE_DIR/skydns_configured";
NETWORK_INSTALLED=`cat $PATH_CONFIGURE_DIR/network_installed`

ETCD_PORT_CLIENT='2379';

# Start etcd?
while ! nc -vz 127.0.0.1 $ETCD_PORT_CLIENT; do
    sleep 1;
done;

# First start?
while true; do
    sleep 1;
    DNS_IP=`cat $PATH_CONFIGURE_DIR/dns-host`;
    MASTER_IP=`cat $CLUSTER_INSTALLED`;
    HOST_IP=`cat /etc/systemd/network/$NETWORK_INSTALLED.network | grep 'Address' | sed s#"Address="##g | awk -F '/' ' {print $1} '`;

    if [ -e "$CLUSTER_INSTALLED" -a -e "$PATH_CONFIGURE_DIR/dns-host" ];then
        # Configure skydns
        if [[ $MASTER_IP == 'single' ]];then
            echo "Configuring skydns.";
            etcdctl set /skydns/config '{"dns_addr":"0.0.0.0:53", "nameservers": ["'$DNS_IP':53"]}';
            if [ $? -ne 0 ];then
                echo "ERROR: Skydns is not configured.";
                continue;
            fi;
        fi;
        echo "Removing 'hostname' key.";
        etcdctl updatedir --ttl=1 /skydns/local/smilart/`hostname`;
        sleep 2;
        echo "Adding hostname.";
        etcdctl set /skydns/local/smilart/`hostname`/$HOST_IP '{"host":"'$HOST_IP'","group":"host"}';
        if [[ $? == 0 ]];then
           break
        fi;
    fi;
done;
