#!/bin/bash

for CONTAINER_NAME in `docker ps -q -f label=com.smilart.service.name`; do
	COM_SMILART_SERVICE_NAME=`docker inspect -f '{{index .Config.Labels "com.smilart.service.name"}}' $CONTAINER_NAME`;
	COM_SMILART_HOSTNAME=`docker inspect -f '{{index .Config.Labels "com.smilart.hostname"}}' $CONTAINER_NAME`;
	COM_SMILART_SERVICE_PORT=`docker inspect -f '{{index .Config.Labels "com.smilart.service.port"}}' $CONTAINER_NAME`;
    	if [[ -n `/usr/bin/curl -s http://127.0.0.1:2379/v2/keys/services/$COM_SMILART_SERVICE_NAME | grep errorCode` ]]; then
		curl -s http://127.0.0.1:2379/v2/keys/services -XPUT -d dir=true;
		curl -s http://127.0.0.1:2379/v2/keys/services/$COM_SMILART_SERVICE_NAME -XPUT -d dir=true;
	fi;
    	curl -s http://127.0.0.1:2379/v2/keys/services/$COM_SMILART_SERVICE_NAME/$COM_SMILART_HOSTNAME -XPUT -d dir=true >/dev/null;
    	curl -s http://127.0.0.1:2379/v2/keys/services/$COM_SMILART_SERVICE_NAME/$COM_SMILART_HOSTNAME/$COM_SMILART_HOSTNAME -XPUT -d value=$COM_SMILART_HOSTNAME >/dev/null;
    	curl -s http://127.0.0.1:2379/v2/keys/services/$COM_SMILART_SERVICE_NAME/$COM_SMILART_HOSTNAME/$COM_SMILART_SERVICE_PORT -XPUT -d value=$COM_SMILART_SERVICE_PORT >/dev/null;
    	curl -s http://127.0.0.1:2379/v2/keys/services/$COM_SMILART_SERVICE_NAME/$COM_SMILART_HOSTNAME -XPUT -d ttl=11 -d dir=true -d prevExist=true >/dev/null;
    	echo "Create $COM_SMILART_HOSTNAME node in etcd"; 
done;
